# crates/api/Cargo.toml

[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
defs.workspace = true
index.workspace = true
snafu.workspace = true
storage.workspace = true
tempfile.workspace = true
uuid.workspace = true
