# crates/tui/Cargo.toml

[package]
name = "tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api.workspace = true
color-eyre.workspace = true
crossterm.workspace = true
defs.workspace = true
dotenv.workspace = true
index.workspace = true
ratatui.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
storage.workspace = true
tokio.workspace = true
uuid.workspace = true
