# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import vector_db_pb2 as vector__db__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertVector = channel.unary_unary(
                '/vectordb.VectorDB/InsertVector',
                request_serializer=vector__db__pb2.InsertVectorRequest.SerializeToString,
                response_deserializer=vector__db__pb2.PointID.FromString,
                _registered_method=True)
        self.DeletePoint = channel.unary_unary(
                '/vectordb.VectorDB/DeletePoint',
                request_serializer=vector__db__pb2.PointID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPoint = channel.unary_unary(
                '/vectordb.VectorDB/GetPoint',
                request_serializer=vector__db__pb2.PointID.SerializeToString,
                response_deserializer=vector__db__pb2.Point.FromString,
                _registered_method=True)
        self.SearchPoints = channel.unary_unary(
                '/vectordb.VectorDB/SearchPoints',
                request_serializer=vector__db__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__db__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.InsertVectorsBatch = channel.unary_unary(
                '/vectordb.VectorDB/InsertVectorsBatch',
                request_serializer=vector__db__pb2.InsertVectorsBatchRequest.SerializeToString,
                response_deserializer=vector__db__pb2.InsertVectorsBatchResponse.FromString,
                _registered_method=True)
        self.SearchPointsBatch = channel.unary_unary(
                '/vectordb.VectorDB/SearchPointsBatch',
                request_serializer=vector__db__pb2.SearchPointsBatchRequest.SerializeToString,
                response_deserializer=vector__db__pb2.SearchPointsBatchResponse.FromString,
                _registered_method=True)


class VectorDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertVector(self, request, context):
        """Insert a vector with a payload and return the assigned PointID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePoint(self, request, context):
        """Delete a vector by its PointID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoint(self, request, context):
        """Get a vector and its payload by PointID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPoints(self, request, context):
        """Search for the k nearest vectors to a target vector given a distance function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertVectorsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPointsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertVector': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVector,
                    request_deserializer=vector__db__pb2.InsertVectorRequest.FromString,
                    response_serializer=vector__db__pb2.PointID.SerializeToString,
            ),
            'DeletePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePoint,
                    request_deserializer=vector__db__pb2.PointID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoint,
                    request_deserializer=vector__db__pb2.PointID.FromString,
                    response_serializer=vector__db__pb2.Point.SerializeToString,
            ),
            'SearchPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPoints,
                    request_deserializer=vector__db__pb2.SearchRequest.FromString,
                    response_serializer=vector__db__pb2.SearchResponse.SerializeToString,
            ),
            'InsertVectorsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVectorsBatch,
                    request_deserializer=vector__db__pb2.InsertVectorsBatchRequest.FromString,
                    response_serializer=vector__db__pb2.InsertVectorsBatchResponse.SerializeToString,
            ),
            'SearchPointsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPointsBatch,
                    request_deserializer=vector__db__pb2.SearchPointsBatchRequest.FromString,
                    response_serializer=vector__db__pb2.SearchPointsBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectordb.VectorDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectordb.VectorDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/InsertVector',
            vector__db__pb2.InsertVectorRequest.SerializeToString,
            vector__db__pb2.PointID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/DeletePoint',
            vector__db__pb2.PointID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/GetPoint',
            vector__db__pb2.PointID.SerializeToString,
            vector__db__pb2.Point.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/SearchPoints',
            vector__db__pb2.SearchRequest.SerializeToString,
            vector__db__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertVectorsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/InsertVectorsBatch',
            vector__db__pb2.InsertVectorsBatchRequest.SerializeToString,
            vector__db__pb2.InsertVectorsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPointsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/SearchPointsBatch',
            vector__db__pb2.SearchPointsBatchRequest.SerializeToString,
            vector__db__pb2.SearchPointsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
